### ISSUE TITLE
Module build failed: TypeError: Must be an object

### ISSUE THREAD

**Issue by itxuye** [ant-design/ant-design-mobile#1067]
#### Environment
mac
node 6.9.2
webpack: 2.x
antd-mobile version:1.0.6

```
WARNING in ./~/antd-mobile/lib/icon/style/assets/right.svg
Module build failed: TypeError: Must be an object
    at exports.objectToAttrString (/Users/itxuye/Desktop/Web/cloudpense-h5/node_modules/svg-sprite-loader/lib/utils.js:6:11)
    at SVGDocument.toString (/Users/itxuye/Desktop/Web/cloudpense-h5/node_modules/svg-sprite-loader/lib/svg-document.js:29:18)
    at Object.module.exports (/Users/itxuye/Desktop/Web/cloudpense-h5/node_modules/svg-sprite-loader/index.js:56:17)
 @ ./~/antd-mobile/lib/icon/style/assets ^\.\/.*\.svg$
 @ ./~/antd-mobile/lib/icon/index.web.js
 @ ./~/antd-mobile/lib/toast/index.web.js
```

```
const svgDirs = [
  require.resolve('antd-mobile').replace(/warn\.js$/, ''),  // 1. 属于 antd-mobile 内置 svg 文件
  // path.resolve(__dirname, 'src/my-project-svg-foler'),  // 2. 自己私人的 svg 存放目录
];

 module: {
    rules: [
      {
        test: /\.(svg)$/i,
        loader: 'svg-sprite-loader',
        include: svgDirs,  // 把 svgDirs 路径下的所有 svg 文件交给 svg-sprite-loader 插件处理
      }
]}
```

**Comment by paranoidjk** [comment]
- https://github.com/kisenka/svg-sprite-loader/issues/18 可能是svg文件被两个loader处理了
- 以及试过webpack 1.x ok吗？

**Comment by paranoidjk** [comment]
https://github.com/kisenka/svg-sprite-loader/issues/31

**Comment by itxuye** [comment]
@paranoidjk Thanks. I used ***file-loader*** before.

**Comment by paranoidjk** [comment]
@itxuye  Sugget you close the issue If the problem is solved.
