### ISSUE TITLE
服务器渲染问题

### ISSUE THREAD

**Issue by bdcwq** [ant-design/ant-design-mobile#255]
#### 本地环境

-   "version": "0.8.2"
-  MacOSX 10.11.6
- Chrome

#### 你做了什么？

import {TabBar} from 'antd-mobile'

.babelrc

{
  "presets": ["es2015", "stage-0", "react"],
  "plugins": ["add-module-exports", "transform-runtime", ["antd", [{style: true, libraryDirectory:"lib", libraryName:"antd"},{style: true, libraryDirectory: "lib", libraryName: "antd-mobile"}]]]
}

#### 你期待的结果是：

服务器渲染

#### 实际上的结果：

webpakck打包的时候提示

ERROR in ./app/containers/App.jsx
Module not found: Error: Cannot resolve module 'antd-mobile/lib/tab-bar' in /Users/bjcwq/Develop/project/weifriend/src/WeiFriendWebApp/app/containers
 @ ./app/containers/App.jsx 9:14-48

运行的时候提示

Server-Render Error Occurs: Error: Cannot find module 'react-native'
    at Function.Module._resolveFilename (module.js:327:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at Object.<anonymous> (index.js:7:20)
    at Module._compile (module.js:399:26)
    at loader (/Users/bjcwq/Develop/project/weifriend/src/WeiFriendWebApp/node_modules/babel-register/lib/node.js:148:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/bjcwq/Develop/project/weifriend/src/WeiFriendWebApp/node_modules/babel-register/lib/node.js:158:7)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at Object.<anonymous> (/Users/bjcwq/Develop/project/weifriend/src/WeiFriendWebApp/app/containers/App.jsx:7:14)
    at Module._compile (module.js:399:26)
    at loader (/Users/bjcwq/Develop/project/weifriend/src/WeiFriendWebApp/node_modules/babel-register/lib/node.js:148:5)
    at Object.require.extensions.(anonymous function) [as .jsx] (/Users/bjcwq/Develop/project/weifriend/src/WeiFriendWebApp/node_modules/babel-register/lib/node.js:158:7)

**Comment by yiminghe** [comment]
目前不支持服务器端渲染

**Comment by bdcwq** [comment]
hi，我使用了"babel-plugin-antd" "version": "0.5.1" 来翻译我的代码，但是遇到一个问题，在webpack的时候提示找不到模块antd-mobile/lib/tar-bar， 我去这个node_modules下面的这个目录查看，发现没有相应的index.js文件。
