### ISSUE TITLE
React Server Render Error on 2.1.10

### ISSUE THREAD

**Issue by a407121393** [ant-design/ant-design-mobile#2583]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.1.10

### Environment
node v9.8  react 16.2.0

### Reproduction link
[https://github.com/ant-design/ant-design-mobile/blob/master/components/input-item/CustomKeyboard.tsx](https://github.com/ant-design/ant-design-mobile/blob/master/components/input-item/CustomKeyboard.tsx)

### Steps to reproduce
React server render not work on version 2.1.10

### What is expected?
Node express can start.

### What is actually happening?
node ./bin/app.js

D:\GitLab Code\exchanges-site_dev\build\node_modules\antd-mobile\lib\input-item\CustomKeyboard.js:51
var IS_IOS = /iphone|ipad|ipod/i.test(window.navigator.userAgent);
                                      ^
ReferenceError: window is not defined
    at Object.<anonymous> (D:\GitLab Code\exchanges-site_dev\build\node_modules\antd-mobile\lib\input-item\CustomKeyboard.js:51:39)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\GitLab Code\exchanges-site_dev\build\node_modules\antd-mobile\lib\input-item\CustomInput.js:37:23)
    at Module._compile (module.js:652:30)
D:\GitLab Code\exchanges-site_dev\build警告: Missing git support, install posh-git with 'Install-Module posh-git' and restart cmder.

**Comment by warmhug** [comment]
需要判断 `typeof window !== 'undefined'` 吗？我看 组件代码(包括 antd) 里用到 window 对象属性的地方、很多没特意做这个判断。cc @paranoidjk @yesmeck

**Comment by yesmeck** [comment]
https://github.com/ant-design/ant-design/search?q=window&unscoped_q=window

**Comment by warmhug** [comment]
@yesmeck 什么意思？看这里
https://github.com/ant-design/ant-design/blob/9552f80cde05e0d0026597053e1b60741cc1b697/components/button/button.tsx#L105
https://github.com/ant-design/ant-design/blob/9552f80cde05e0d0026597053e1b60741cc1b697/components/input/TextArea.tsx#L7

**Comment by yesmeck** [comment]
`componentWillReceiveProps` 不会在服务端执行的，所以没关系。其他会在服务端执行的地方要判断。

**Comment by warmhug** [comment]
Ref: #1059 #1077 #1079 #1305
