### ISSUE TITLE
Cannot find module '../style/images/arrow.png' from 'ListItem.native.js'

### ISSUE THREAD

**Issue by zhaozhiming** [ant-design/ant-design-mobile#2608]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Version
2.1.7

### Environment
Mac OS Hight sierra 10.13.2, React-Native 0.55.2

### Reproduction link
[https://github.com/zhaozhiming/antd-mobile-listitem-bug](https://github.com/zhaozhiming/antd-mobile-listitem-bug)

### Steps to reproduce
```sh
yarn install 
yarn test
```
And there is the error：

```sh
yarn run v1.5.1
$ jest
 FAIL  ./App.test.js
  ✕ renders without crashing (250ms)

  ● renders without crashing

    Cannot find module '../style/images/arrow.png' from 'ListItem.native.js'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:169:17)
      at Item.render (node_modules/antd-mobile/lib/list/ListItem.native.js:223:92)
      at finishClassComponent (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:3940:33)
      at updateClassComponent (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:3908:12)
      at beginWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:4529:16)

  console.error node_modules/react-test-renderer/cjs/react-test-renderer.development.js:5190
    The above error occurred in the <Item> component:
        in Item (created by App)
        in View (created by Component)
        in Component (created by List)
        in View (created by Component)
        in Component (created by List)
        in List (created by App)
        in View (created by Component)
        in Component (created by App)
        in App

    Consider adding an error boundary to your tree to customize error handling behavior.
    Visit https://fb.me/react-error-boundaries to learn more about error boundaries.

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        1.193s, estimated 3s
Ran all test suites.
error An unexpected error occurred: "Command failed.
```

### What is expected?
run test successful

### What is actually happening?
run test failed

---
I found `antd-mobile/lib/list/ListItem.native.js` require('../style/images/arrow.png'), but files in `../style/images` are `arrow@2x.png`  and `arrow@2x.png` but not `arrow.png`.

**Comment by warmhug** [comment]
cc @silentcloud

**Comment by silentcloud** [comment]
@zhaozhiming  你 jest 跑应该是没配置相关 png 文件的依赖吧？  require('../style/images/arrow.png') 会自动找 @2x 和 3x 图，http://facebook.github.io/react-native/docs/images.html#static-image-resources

检查你 jest 配置
