### ISSUE TITLE
next export 导致会崩溃

### ISSUE THREAD

**Issue by fangkyi03** [ant-design/ant-design-mobile#3268]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/zeit/next.js/tree/canary/examples/with-antd-mobile](https://github.com/zeit/next.js/tree/canary/examples/with-antd-mobile)

### Steps to reproduce
npm run export以后提示崩溃
node_modules/_normalize.css@7.0.0@normalize.css/normalize.css:12
html {
     ^

SyntaxError: Unexpected token {
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)

### What is expected?
两个问题
1.npm run export 以后能正常使用
2.使用normalize.css会导致页面样式异常 因为会修改html的样式 导致没有撑大

### What is actually happening?
npm run dev 跟 npm run build 都是正常的 但是npm run export就是不行
我这边是使用Less的 所以要配合less使用 没有办法直接使用css

| Environment | Info |
|---|---|
| antd | 2.2.12 |
| React | 16.8.4 |
| System | mac |
| Browser | chrome 74.0.3729.169 |

**Comment by fangkyi03** [comment]
已经解决 自己重新编译了antd-mobile源码

**Comment by MichaelIT** [comment]
@fangkyi03 请问怎么解决的？
