### ISSUE TITLE
next.js 使用 NoticeBar ：useLayoutEffect does nothing on the server

### ISSUE THREAD

**Issue by atom-shanghai** [ant-design/ant-design-mobile#4166]
Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://reactjs.org/link/uselayouteffect-ssr for common fixes.
    at eval (webpack-internal:///./node_modules/antd-mobile/cjs/components/notice-bar/notice-bar.js:84:40)
    at eval (webpack-internal:///./node_modules/antd-mobile/cjs/components/notice-bar/notice-bar.js:84:40)

**Comment by awmleer** [comment]
Close via 35578b6ef
