### ISSUE TITLE
服务端渲染 / SSR中使用报错

### ISSUE THREAD

**Issue by Przeblysk** [ant-design/ant-design-mobile#4228]
```
:root {
^

SyntaxError: Unexpected token ':'
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/mac/BabyCare/SSRProject/frontend-bckid-wap-ssr2/node_modules/antd-mobile/cjs/global/index.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
```

**Comment by awmleer** [comment]
请提供一下具体的信息哈：

你使用的脚手架是？
antd-mobile 的版本号是？
你是如何在项目中引入 antd-mobile 的？

**Comment by zhangyuang** [comment]
http://doc.ssr-fc.com/docs/api$config#whiteList

**Comment by aioros2016** [comment]
@zhangyuang 你给的这个文档里也没有说清楚whiteList具体应该怎么用啊？

**Comment by zhangyuang** [comment]
> @zhangyuang 你给的这个文档里也没有说清楚whiteList具体应该怎么用啊？

https://doc.ssr-fc.com/docs/api$config#whiteList%F0%9F%A4%94
文档写得很清楚了
