### ISSUE TITLE
[V5]腾讯云函数运行NextJS时出现问题

### ISSUE THREAD

**Issue by ZhelinCheng** [ant-design/ant-design-mobile#4385]
### Version of antd-mobile

^5.0.0-beta.24

### Description

Node:12.16
antdm:5.0.0-beta.24
next:11.1.2
next-transpile-modules:8.0

运行时报下面的错误信息：
```
next-transpile-modules - DEPRECATED - fallbacking to previous module resolution system for module "antd-mobile", you can now just pass the name of the package to transpile and it will detect its real path without you having to pass a sub-module.

Error: next-transpile-modules - an unexpected error happened when trying to resolve "antd-mobile". Are you sure the name module you are trying to transpile is correct, and it has a "main" or an "exports" field?

Error: Can't resolve 'antd-mobile' in '/var/user'

    at getPackageRootDirectory (/opt/node_modules/next-transpile-modules/src/next-transpile-modules.js:173:17)

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)

    at Module.load (internal/modules/cjs/loader.js:1002:32)

    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
```

**Comment by awmleer** [comment]
看起来 5.9.0 和 5.9.1 两次版本发布之后，应该就能解决掉这个问题了

issue 我先关闭了，如果还有问题的话可以再回复一下
