### ISSUE TITLE
Popup组件内，按钮，先关闭Popup，再路由跳转页面，动画未完成，出现react state update on an unmounted component错误。

### ISSUE THREAD

**Issue by liangskyli** [ant-design/ant-design-mobile#4427]
### Version of antd-mobile

5.0.0-beta.31

### Browser and its version

all

### What happened?

Popup组件内，按钮，先关闭Popup，再路由跳转页面，动画未完成，出现react state update on an unmounted component错误。

### Relevant log output

```shell
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    at Mask (http://127.0.0.1:8001/sub-zxkp-h5/mf-dep_vendors-node_modules_antd-mobile_es_index_js.30e1df7d.async.js:18012:79)
    at div
    at Popup (http://127.0.0.1:8001/sub-zxkp-h5/mf-dep_vendors-node_modules_antd-mobile_es_index_js.30e1df7d.async.js:19291:58)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xiaoyao96** [comment]
v5.0.0-rc.2 已修复
