### ISSUE TITLE
弹框类组件动画过程中被卸载，会报错的问题

### ISSUE THREAD

**Issue by xiaoyao96** [ant-design/ant-design-mobile#4478]
### Version of antd-mobile

5.0.0-rc.0

### Sandbox to reproduce
Toast报错demo:
https://codesandbox.io/s/vibrant-heyrovsky-7qgr3

其他弹框类报错demo：
https://codesandbox.io/s/busy-smoke-ze5l9

### What happened?

Toast消失动画过程中，再次触发Toast.show会报错，报错信息如下
我发现很多弹框类组件，动画过程中如果组件被卸载都会有这个问题，例如 #4427。

### Relevant log output

```shell
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    at Mask (https://7qgr3.csb.app/node_modules/antd-mobile/es/components/mask/mask.js:34:57)
    at InternalToast (https://7qgr3.csb.app/node_modules/antd-mobile/es/components/toast/toast.js:24:45)
    at TempToast (https://7qgr3.csb.app/node_modules/antd-mobile/es/components/toast/methods.js:39:46)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xiaoyao96** [comment]
已尝试修复，动画结束onRest，已卸载就不去setVisible

**Comment by xiaoyao96** [comment]
我发现很多弹框类组件，动画过程中如果组件被卸载都会有这个问题，例如 #4427。
