### ISSUE TITLE
使用库中组件报错

### ISSUE THREAD

**Issue by JacksenLaw** [ant-design/ant-design-mobile#4571]
### Version of antd-mobile

5.0.0-rc.5

### Browser and its version

reactnative version : 0.63.4

### Relevant log output

```shell
使用库中组件报错
error: Error: Unable to resolve module ./global.css from D:\code\rn\smartheatinguser_rn\node_modules\antd-mobile\cjs\global\index.js: 

None of these files exist:
  * node_modules\antd-mobile\cjs\global\global.css(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  * node_modules\antd-mobile\cjs\global\global.css\index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  1 | "use strict";
  2 |
> 3 | require("./global.css");
    |          ^
  4 |
  5 | var _canUseDom = require("../utils/can-use-dom");
  6 |
    at ModuleResolver.resolveDependency (D:\code\rn\smartheatinguser_rn\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:168:15)
    at DependencyGraph.resolveDependency (D:\code\rn\smartheatinguser_rn\node_modules\metro\src\node-haste\DependencyGraph.js:353:43)
    at Object.resolve (D:\code\rn\smartheatinguser_rn\node_modules\metro\src\lib\transformHelpers.js:271:42)
    at resolve (D:\code\rn\smartheatinguser_rn\node_modules\metro\src\DeltaBundler\traverseDependencies.js:571:33)
    at D:\code\rn\smartheatinguser_rn\node_modules\metro\src\DeltaBundler\traverseDependencies.js:587:26
    at Array.reduce (<anonymous>)
    at resolveDependencies (D:\code\rn\smartheatinguser_rn\node_modules\metro\src\DeltaBundler\traverseDependencies.js:586:33)
    at D:\code\rn\smartheatinguser_rn\node_modules\metro\src\DeltaBundler\traverseDependencies.js:275:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (D:\code\rn\smartheatinguser_rn\node_modules\metro\src\DeltaBundler\traverseDependencies.js:87:24)
```

**Comment by JacksenLaw** [comment]
使用任何组件都报错

**Comment by awmleer** [comment]
@JacksenLaw 你是 React Native 的项目？antd-mobile v5 不支持 React Native

rn 相关问题请移步：https://github.com/ant-design/ant-design-mobile-rn/issues
