### ISSUE TITLE
和umi集成，启动报错

### ISSUE THREAD

**Issue by mdddj** [ant-design/ant-design-mobile#4592]
### Version of antd-mobile

5.0.0-rc.7

### Description

报错输入：
```bash
AssertionError [ERR_ASSERTION]: filePath not found of /Users/ldd/dd_blog_react/node_modules/antd-mobile/es/badge
    at /Users/ldd/dd_blog_react/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/mfsu/utils.js:119:27
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/ldd/dd_blog_react/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/mfsu/utils.js:64:103)
    at _next (/Users/ldd/dd_blog_react/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/mfsu/utils.js:66:194)
    at /Users/ldd/dd_blog_react/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/mfsu/utils.js:66:364
    at new Promise (<anonymous>)
    at /Users/ldd/dd_blog_react/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/mfsu/utils.js:66:97
    at figureOutExport (/Users/ldd/dd_blog_react/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/mfsu/utils.js:129:17)
    at /Users/ldd/dd_blog_react/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/mfsu/DepBuilder.js:184:201
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/ldd/dd_blog_react/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/mfsu/DepBuilder.js:84:103)
    at _next (/Users/ldd/dd_blog_react/node_modules/umi/node_modules/@umijs/preset-built-in/lib/plugins/features/mfsu/DepBuilder.js:86:194)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by awmleer** [comment]
看起来似乎是 mfsu 的问题，关掉再试试看？
