### ISSUE TITLE
【请求帮助】error: Error: Unable to resolve module ./global.css from

### ISSUE THREAD

**Issue by frljx** [ant-design/ant-design-mobile#4687]
### Version of antd-mobile

5.0.0-rc.17

### Description

使用最新版rn-cli脚手架搭建项目，第一次集成antd-mobile报错如下：
`error: Error: Unable to resolve module ./global.css from F:\workspace\bbtcamera6601\node_modules\antd-mobile\cjs\global\index.js:

None of these files exist:
  * node_modules\antd-mobile\cjs\global\global.css(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  * node_modules\antd-mobile\cjs\global\global.css\index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  1 | "use strict";
  2 |
> 3 | require("./global.css");
    |          ^
  4 |
  5 | var _canUseDom = require("../utils/can-use-dom");
  6 |
    at ModuleResolver.resolveDependency (F:\workspace\bbtcamera6601\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:107:15)
    at DependencyGraph.resolveDependency (F:\workspace\bbtcamera6601\node_modules\metro\src\node-haste\DependencyGraph.js:288:43)
    at Object.resolve (F:\workspace\bbtcamera6601\node_modules\metro\src\lib\transformHelpers.js:129:24)
    at resolve (F:\workspace\bbtcamera6601\node_modules\metro\src\DeltaBundler\traverseDependencies.js:396:33)
    at F:\workspace\bbtcamera6601\node_modules\metro\src\DeltaBundler\traverseDependencies.js:412:26
    at Array.reduce (<anonymous>)
    at resolveDependencies (F:\workspace\bbtcamera6601\node_modules\metro\src\DeltaBundler\traverseDependencies.js:411:33)
    at processModule (F:\workspace\bbtcamera6601\node_modules\metro\src\DeltaBundler\traverseDependencies.js:140:31)
    at async addDependency (F:\workspace\bbtcamera6601\node_modules\metro\src\DeltaBundler\traverseDependencies.js:230:18)
    at async Promise.all (index 0)`

package.json
`{
  "name": "bbtcamera6601",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "antd-mobile": "^5.0.0-rc.17",
    "react": "17.0.2",
    "react-native": "0.66.4",
    "react-native-vector-icons": "^9.0.0"
  },
  "devDependencies": {
    "@babel/core": "^7.16.7",
    "@babel/eslint-parser": "^7.16.5",
    "@babel/preset-env": "^7.16.8",
    "@babel/runtime": "^7.16.7",
    "@react-native-community/eslint-config": "^3.0.1",
    "babel-jest": "^27.4.6",
    "eslint": "^8.6.0",
    "eslint-plugin-flowtype": "^8.0.3",
    "jest": "^27.4.7",
    "metro-react-native-babel-preset": "^0.66.2",
    "next-images": "^1.8.4",
    "next-transpile-modules": "^9.0.0",
    "react-test-renderer": "17.0.2"
  },
  "jest": {
    "preset": "react-native"
  }
}
`

**Comment by awmleer** [comment]
rn？antd-mobile 现在不支持 rn 哈
如果有需求的话可以移步：https://github.com/ant-design/ant-design-mobile-rn

**Comment by frljx** [comment]
@awmleer 是我唐突了 -0-！  十分感谢
