### ISSUE TITLE
 v2 和 v5 两个版本的共存，能正常启动项目，但是build项目时报错。

### ISSUE THREAD

**Issue by nvliderener** [ant-design/ant-design-mobile#5023]
### Version of antd-mobile

5.0.0-rc.10

### Operating system and its version

Others

### Browser and its version

all

### What happened?

无法构建工程

### Relevant log output

```shell
verbose stack Exit status 1
 verbose stack     at EventEmitter.<anonymous> 
 (C:\Users\user\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
 verbose stack     at emitTwo (events.js:126:13)
 verbose stack     at EventEmitter.emit (events.js:214:7)
 verbose stack     at ChildProcess.<anonymous> 
 (C:\Users\user\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
 verbose stack     at emitTwo (events.js:126:13) verbose stack     at ChildProcess.emit 
 (events.js:214:7)
 verbose stack     at maybeClose (internal/child_process.js:925:16)
 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
```

**Comment by awmleer** [comment]
看起来不是 antd-mobile 的报错，请把你的项目工程打包上传一下
