### ISSUE TITLE
Remix error

### ISSUE THREAD

**Issue by tombohub** [ant-design/ant-design-mobile#5231]
### Version of antd-mobile

5.12.6

### Operating system and its version

Others

### Browser and its version

Chrome 101.0.4951.67 (Official Build) (64-bit)

### Sandbox to reproduce

https://stackblitz.com/edit/node-qtgzuc?file=app/routes/index.tsx

### What happened?

There's an error related to css.

I expected to work like documentation says: https://mobile.ant.design/guide/ssr

### Relevant log output

```shell
D:\projects\prototypes\remixindiestack\node_modules\antd-mobile\cjs\global\global.css:1
:root {
^

SyntaxError: Unexpected token ':'
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1031:15)
    at Module._compile (node:internal/modules/cjs/loader:1065:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (D:\PROJEKTI\prototypes\remixindiestack\node_modules\antd-mobile\cjs\global\index.js:3:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (D:\PROJEKTI\prototypes\remixindiestack\node_modules\antd-mobile\cjs\index.js:475:1)
```

**Comment by 3lang3** [comment]
remix需要额外的配置，在做测试了。

**Comment by awmleer** [comment]
This bug is due to #5013, which remove the `exports` field from `package.json`. We'll try to find another solution for Remix.

**Comment by 3lang3** [comment]
@tombohub [remix template](https://github.com/3lang3/antd-mobile-template/tree/main/remix) try this tempalte

**Comment by tombohub** [comment]
@3lang3 I got error:

```
Error: Cannot find module 'rc-field-form'
Require stack:
- C:\antmobile\build\index.js
- C:\antmobile\node_modules\@remix-run\serve\index.js
- C:\antmobile\node_modules\@remix-run\dev\cli\commands.js
- C:\antmobile\node_modules\@remix-run\dev\cli\run.js
- C:\antmobile\node_modules\@remix-run\dev\cli\index.js
- C:\antmobile\node_modules\@remix-run\dev\index.js
- C:\antmobile\node_modules\@remix-run\dev\cli.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\Shmukaluka\Desktop\ddd\node_modules\antd-mobile\bundle\antd-mobile.es.js:11:66)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
```

do you have any error?

**Comment by 3lang3** [comment]
@tombohub 

Using antd-mobile in Remix requires some additional configuration.

Add antd-mobile config in `tsconfig.json` `compilerOptions.paths` field, Add `global.d.ts` in `include` field:

```json
{
  "include": ["remix.env.d.ts", "global.d.ts", "**/*.ts", "**/*.tsx"],
  "compilerOptions": {
    ...
    "paths": {
      "antd-mobile": ["node_modules/antd-mobile/bundle/antd-mobile.es.js"]
    }
  }
}
```

Add `global.d.ts` file in project root dir.

```ts
declare module 'antd-mobile' {
  export * from 'antd-mobile/es';
}
```

Import style file in `app/root.tsx`:

```ts
import styles from "antd-mobile/bundle/style.css";

export function links() {
  return [{ rel: "stylesheet", href: styles }];
}
```

**Comment by awmleer** [comment]
@tombohub [Here](https://github.com/ant-design/ant-design-mobile/pull/5234/files) is the latest updated doc, which has not been published yet.

**Comment by awmleer** [comment]
But the error `Error: Cannot find module 'rc-field-form'` is somehow strange… `antd-mobile` has already declared `rc-field-form` in dependencies. So npm should have automatically installed it for you. Maybe upload a reproducible project?

**Comment by 3lang3** [comment]
> But the error `Error: Cannot find module 'rc-field-form'` is somehow strange… `antd-mobile` has already declared `rc-field-form` in dependencies. So npm should have automatically installed it for you. Maybe upload a reproducible project?

I test form component in my template repo, everything fine with yarn & pnpm.

I got issue `Cannot find module 'ahooks'` when use npm first time, and then retry  many times `npm install` (rm `node_modules` and `package-lock.json`). no error throw.

so @tombohub are you using npm ?

**Comment by tombohub** [comment]
@awmleer how can I upload? I downloaded this [template](https://github.com/3lang3/antd-mobile-template/tree/main/remix) and then run `npm install`. Do you want me to upload with all the node_modules folder?

@3lang3 yes, I am using npm

**Comment by awmleer** [comment]
+1 Seems like to be a problem with npm.
