### ISSUE TITLE
Ellipsis增加useMemo之后，导致项目报错，原本content属性可以为空，现在空了之后直接抛异常了

### ISSUE THREAD

**Issue by yochor** [ant-design/ant-design-mobile#5726]
### Version of antd-mobile

5.24.0

### Operating system and its version

iOS, Android, Others

### Browser and its version

any

### Sandbox to reproduce

[demo](https://codesandbox.io/s/gallant-julien-92hxb4)

### What happened?

升级到5.24.0版本之后项目访问直接报错
Uncaught Error: string cannot be undefined or null
查阅代码之后发现是Ellipsis组件增加useMemo之后，原本content属性可以为空(undefined)，现在空了之后直接抛异常了

### Relevant log output

```shell
mf-dep_vendors-node_modules_antd-mobile_es_index_js.d698b618.async.js:40580 Uncaught Error: string cannot be undefined or null
    at runes (mf-dep_vendors-node_modules_antd-mobile_es_index_js.d698b618.async.js:40580:11)
    at mf-dep_vendors-node_modules_antd-mobile_es_index_js.d698b618.async.js:13344:56
    at mountMemo (mf-dep_vendors-node_modules_react-dom_index_js.107dc564.async.js:15855:19)
    at Object.useMemo (mf-dep_vendors-node_modules_react-dom_index_js.107dc564.async.js:16228:16)
    at useMemo (mf-dep_vendors-node_modules_react_index_js.65bcbee5.async.js:1642:21)
    at Ellipsis (mf-dep_vendors-node_modules_antd-mobile_es_index_js.d698b618.async.js:13343:61)
```

**Comment by afc163** [comment]
来个重现？

**Comment by afc163** [comment]
重现指的是类似 codesandbox 的在线可访问演示，不是一段代码片段。
