### ISSUE TITLE
为什么使用Carousel 报这个错误Minified React error #290

### ISSUE THREAD

**Issue by enjoy-2021** [ant-design/ant-design-mobile#5841]
### Version of antd-mobile

2.3.4 

### Description

react使用16.14.0的时候，使用Carousel报这个错误，使用antd-mobile的其他组件无此问题
Error: Minified React error #290; visit https://reactjs.org/docs/error-decoder.html?invariant=290&args[]=slider for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Mi (production.1ec2f90001693c9a92cb.js:2:1026698)
    at production.1ec2f90001693c9a92cb.js:2:1031143
    at Ac (production.1ec2f90001693c9a92cb.js:2:1041155)
    at Uc (production.1ec2f90001693c9a92cb.js:2:1045344)
    at Bc (production.1ec2f90001693c9a92cb.js:2:1045042)
    at ka (production.1ec2f90001693c9a92cb.js:2:1080869)
    at ys (production.1ec2f90001693c9a92cb.js:2:1072292)
    at ms (production.1ec2f90001693c9a92cb.js:2:1072217)
    at ss (production.1ec2f90001693c9a92cb.js:2:1069229)
    at production.1ec2f90001693c9a92cb.js:2:1020591 {componentStack: '\n    in Carousel\n    in Carousel\n    in div\n    in…   in t\n    in t\n    in t\n    in n\n    in Unknown'}

**Comment by miracles1919** [comment]
v2 已停止维护了，建议用 v5
