### ISSUE TITLE
nextjs ssr SpinLoading 组件报错

### ISSUE THREAD

**Issue by fourcels** [ant-design/ant-design-mobile#5974]
### Version of antd-mobile

^5.28.0

### Relevant log output

```shell
Error: Missing getServerSnapshot, which is required for server-rendered content. Will revert to client rendering.
    at Object.useSyncExternalStore (/Users/kiyan/Documents/react-workspace/my-app/node_modules/.pnpm/next@13.1.6_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/compiled/react-dom/cjs/react-dom-server.browser.development.js:7225:11)
    at useSyncExternalStore (/Users/kiyan/Documents/react-workspace/my-app/node_modules/.pnpm/next@13.1.6_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/compiled/react/cjs/react.development.js:1807:21)
    at useMotionReduced (webpack-internal:///(sc_client)/./node_modules/.pnpm/antd-mobile@5.28.0_biqbaboplfbrettd7655fr4n2y/node_modules/antd-mobile/es/utils/reduce-and-restore-motion.js:38:92)
    at eval (webpack-internal:///(sc_client)/./node_modules/.pnpm/antd-mobile@5.28.0_biqbaboplfbrettd7655fr4n2y/node_modules/antd-mobile/es/components/spin-loading/spin-loading.js:30:107)
```

**Comment by miracles1919** [comment]
来个复现仓库看看，我自己试了下是可以的， https://github.com/miracles1919/antd-mobile-examples

**Comment by fourcels** [comment]
@miracles1919 
<SpinLoading /> 是这个组件会有问题

**Comment by miracles1919** [comment]
感觉跟 `useSyncExternalStore` 相关

**Comment by HuberTRoy** [comment]
@miracles1919 

这个好像是因为react-spring= =，直接用SVG(或者CSS)动画？代码也很简洁，`--percent`目前没有暴露出去不需要反馈数值感觉是可以不用react-spring的。

```
      <svg className={`${classPrefix}-svg`} viewBox='0 0 32 32'>
        <circle
          className={`${classPrefix}-fill`}
          fill='transparent'
          strokeWidth='2'
          strokeDasharray={circumference}
          strokeDashoffset={80}
          strokeLinecap='square'
          r={15}
          cx={16}
          cy={16}
        >
          <animate
            attributeName='stroke-dashoffset'
            values='80;30;80'
            dur='2.4s'
            repeatCount='indefinite'
          />
        </circle>
      </svg>
```
