### ISSUE TITLE
垃圾玩意 用不了

### ISSUE THREAD

**Issue by sopaco** [ant-design/ant-design-mobile#693]
> antd-init方式找不到组件

> dva方式startup运行报错
```txt
> @ start /Users/MacHewleet/Workspace/SAW_S/testtest
> roadhog server

/Users/MacHewleet/Workspace/SAW_S/testtest/node_modules/roadhog/bin/roadhog.js:9
const [major, minor] = nodeVersion.split('.');
      ^

SyntaxError: Unexpected token [
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
```

**Comment by afc163** [comment]
@sorrycc

**Comment by sorrycc** [comment]
node 需要 0.6.5 以上。

**Comment by sorrycc** [comment]
![image](https://cloud.githubusercontent.com/assets/35128/21580703/070362e8-d047-11e6-9205-3b164d8fcc0c.png)

发布 roadhog@0.4.2，会做 node 版本的前置提示了。
